name: foodie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_spinkit: ^5.2.0
  dio: ^5.4.0
  dotenv: ^4.2.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  convex_bottom_bar: ^3.2.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

