name: foodie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  convex_bottom_bar: ^3.2.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21

flutter: 
  uses-material-design: true

